services:
  church-bot:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DEBIAN_FRONTEND=noninteractive
        - TZ=Europe/Minsk
    container_name: church-schedule-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ..:/app/project:ro  # Keep this read-only for safety
      - ./logs:/app/logs
      - ./data:/app/data
      - ./backups:/app/backups  # Added dedicated backups volume
      - ./ssh:/app/ssh:ro
      - church_temp:/tmp
    healthcheck:
      test: ["CMD", "python", "-c", "import os; exit(0 if os.path.exists('/app/bot.py') else 1)"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    tty: true
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 128M
    # Для поддержки подключения по SSH
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0

networks:
  app-network:
    driver: bridge

volumes:
  church_temp:
    driver: local